### ISSUE TITLE
Mac--Request for Password for Tor Bundle Instalation

### ISSUE THREAD

**Issue by y0d31** [susmithHCK/torghost#10]
Hi guys,

I followed the steps of the installation and while running ./install.sh I got an error asking for the password for tor bundle. Therefore I need that password in order to complete the installation.

I am using the tor on a Mac/OS system and therefore I need help for this installation.

Cheers,
IonutC

**Comment by y0d31** [comment]
![screen shot 2017-05-15 at 11 04 57 pm](https://cloud.githubusercontent.com/assets/22478094/26076896/f69953b4-39c2-11e7-9607-7bbc1816666f.png)

**Comment by ruped24** [comment]
It's asking for you sudo or root password.

**Comment by jmfgdev** [comment]
This is the expected behavior ^

**Comment by ruped24** [comment]
@jmfgdev yes.

**Comment by jmfgdev** [comment]
Will that function even work on macos? Won't it call a apt command?

**Comment by ruped24** [comment]
@jmfgdev You are right, it's calling apt-get.  Also I don't think iptables rules will work with a native mac.

**Comment by jmfgdev** [comment]
Yes I was thinking about up tables, @y0d31 please stop trying to run it it's not compatible, and broken to begin with
