### ISSUE TITLE
Randomly starts on Debian Jessie, 100% CPU utilization

### ISSUE THREAD

**Issue by yogyakor** [susmithHCK/torghost#11]
As per title, top command randomly reports a 'tor' process in my laptop that uses up to 100% of CPU.
This is several reboots after the last use of torghost. 
Torghost has been cleanly stopped via command line (torghost stop) last time it was used.

**Comment by yogyakor** [comment]
How do I remove this from my Debian based system?

**Comment by jmfgdev** [comment]
Hey I can help you with this, do this is your console

whereis torghost

if you get no directory, do

whereis tor

And then try sudo apt remove tor

I will note, TOR doesn't use that much cpu, and I see nothing in this package that would cause tor to randomly start. You might be infected with some other linux malware, try using ClamAV on /
