### ISSUE TITLE
Fetching IP Address Constantly

### ISSUE THREAD

**Issue by Darth4212** [susmithHCK/torghost#12]
Whenever I run `sudo torghost start` it gets stuck at `Fetching current IP` but for some reason when I run `sudo torghost stop` it fetches the ip fairly quickly

**Comment by jmfgdev** [comment]
This project breaks DNS and simultaneously doesn't anonymize it, sorry, don't know what else to tell you.

I've tried to explain it to the dev but he is sure his code is perfect regardless of the demonstrable issue

**Comment by susmithHCK** [comment]
FIXED WITH NEW UPDATE

**Comment by azamet90** [comment]
year 2020 still same problem :D

**Comment by JimmyByte** [comment]
Oof
