### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by barmaanb1383** [susmithHCK/torghost#16]
root@anonymous-device:~/Desktop/Git/torghost# torghost
Traceback (most recent call last):
  File "/usr/bin/torghost", line 9, in <module>
    from stem import Signal
ImportError: No module named stem

**Comment by Defalt2** [comment]
same error

**Comment by zpsmack** [comment]
I got the error

**Comment by MiniuBoo** [comment]
me too

**Comment by susmithHCK** [comment]
# pip install stem

This may solve the issue
