### ISSUE TITLE
torghost error

### ISSUE THREAD

**Issue by MeanMachine123** [susmithHCK/torghost#18]
Traceback (most recent call last):
  File "/usr/bin/torghost", line 9, in <module>
    from stem import Signal
ImportError: No module named stem

How can I solve this issue....???

apt-get install tor already updated........

**Comment by MeanMachine123** [comment]
Dude,

           I have resolved the issue by pip install stem.Thank You for your reply.




Regards,

Mean Machine

________________________________

**Comment by SQLprodigy** [comment]
Please elaborate sir as I am having the same issue.

**Comment by MeanMachine123** [comment]
pip install stem

________________________________

**Comment by MeanMachine123** [comment]
apt-get install tor

________________________________

**Comment by MeanMachine123** [comment]
https://github.com/ruped24/toriptables2

[https://avatars1.githubusercontent.com/u/12942791?v=4&s=400]<https://github.com/ruped24/toriptables2>

GitHub - ruped24/toriptables2: Tor Iptables script is an ...<https://github.com/ruped24/toriptables2>
github.com
toriptables2 - Tor Iptables script is an anonymizer that sets up iptables and tor to route all services and traffic including DNS through the Tor network.



________________________________

**Comment by SQLprodigy** [comment]
What do you mean PIP install stem? i ran that command , nothing.
