### ISSUE TITLE
error again :(

### ISSUE THREAD

**Issue by Defalt2** [susmithHCK/torghost#19]
i installed stem but i still get the error 
Traceback (most recent call last):
  File "/usr/bin/torghost", line 9, in <module>
    from stem import Signal
ImportError: No module named stem

**Comment by jmfgdev** [comment]
What version of Python are you running there?

**Comment by jmfgdev** [comment]
On second thought, it would seem this commit would fix your issue,

https://github.com/susmithHCK/torghost/commit/6197412c2707d1c0b76821095ba39521f4f39bde

Can you try git pulling the latest changes and rerunning?/reinstalling?

**Comment by susmithHCK** [comment]
im using the beloved python 2.7

**Comment by Defalt2** [comment]
still get error 
i am using python3.5

**Comment by jmfgdev** [comment]
@Defalt2 You might have to install stem and the dependencies again now that you have pip3 rather than pip for python 2

**Comment by zippos** [comment]
```
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
python -m pip install stem
torghost start
```
