### ISSUE TITLE
Some network commands like ping, traceroute fail

### ISSUE THREAD

**Issue by igot5onit** [susmithHCK/torghost#20]
Some network related commands fail when torghost is active. However, when using without active torghost or routing traffic through tor using proxychains the commands run without issues.

Examples below:

$ ping www.google.com
PING www.google.com (216.58.212.196) 56(84) bytes of data.
From 192.168.1.117 (192.168.1.117) icmp_seq=1 Destination Port Unreachable
ping: sendmsg: Operation not permitted
From 192.168.1.117 (192.168.1.117) icmp_seq=2 Destination Port Unreachable
ping: sendmsg: Operation not permitted
From 192.168.1.117 (192.168.1.117) icmp_seq=3 Destination Port Unreachable
ping: sendmsg: Operation not permitted
^C
--- www.google.com ping statistics ---
3 packets transmitted, 0 received, +3 errors, 100% packet loss, time 2014ms

$ traceroute www.google.com
traceroute to www.google.com (216.58.212.196), 30 hops max, 60 byte packets
send: Operation not permitted

I suspect this may have something to do with the iptables commands in the torghost script?

Since these commands work fine through tor when used with proxychains, I guess the issue lies within torghost rather than icmp traffic not going through tor?

Also nmap fails similarly since it uses ping and traceroute.

Just some thoughts behind my reasoning, please correct and pardon me if I may be wrong. I am just a novice student.

**Comment by varun2906** [comment]
I'm getting the same error. Please reply if anyone gets the solution!

**Comment by susmithHCK** [comment]
Ping wont work, Its blocked because it compromises anonymity
