### ISSUE TITLE
How to Change IP Address on Torghost to a Specific Country

### ISSUE THREAD

**Issue by dhrubo11** [susmithHCK/torghost#21]
How to Change IP Address on Torghost to a Specific Country

**Comment by Andiansyah23** [comment]
Not able to do that, cause it will bounce randomly 
#CMIIW

**Comment by susmithHCK** [comment]
It doesn't have that function. If you want to add that, pull request and edit my code, thank you. :D

**Comment by Andiansyah23** [comment]
If you willing :D i will try :X

Pada tanggal 10 Nov 2017 14:41, "susmithHCK" <notifications@github.com>
menulis:
