### ISSUE TITLE
Does all tools work with torghost

### ISSUE THREAD

**Issue by 143Sarika** [susmithHCK/torghost#23]
I am not sure, If all pentesting tools (i.e Armitage, Metasploit, Nmap) would work fine with torghost or not. Please clarify.

**Comment by susmithHCK** [comment]
Yes everything will be through tor. 
Note: u cant use reverse_shell via tor

**Comment by hybla0** [comment]
@SusmithKrishnan > Note: u cant use reverse_shell via tor.
These guys did it ;)
https://github.com/febrezo/netcator
