### ISSUE TITLE
Error in torghost start in manjaro 

### ISSUE THREAD

**Issue by farzamkhan** [susmithHCK/torghost#24]
hi 
i download torghost and install it. but i have problem in start it with this error 

  File "/usr/bin/torghost", line 30
    print ""
           ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("")?

**Comment by susmithHCK** [comment]
this is for python 2.7

**Comment by farzamkhan** [comment]
tnx . i must install python 2.7 and remove python 3 ?

**Comment by slrslr** [comment]
> i must install python 2.7 and remove python 3 ?
i would be worried about removing python. I think i did it once and ruined my OS. Two versions should work in parallel, there are guides on how to do it.
