### ISSUE TITLE
Error Torghost v2.0 in Kali Linux

### ISSUE THREAD

**Issue by igoreduardo** [susmithHCK/torghost#25]
[00:48:19] Torrc file already configured
[00:48:19] Configuring DNS resolv.conf file..  [done]
[00:48:19] Starting tor service..  [done]
[00:48:20] setting up iptables rules [done]
[00:48:20] Fetching current IP...
[00:48:20] CURRENT IP : 

Server not found

Firefox can’t find the server at www.google.com.br.

torghost switch
[00:49:23] Please wait...
[00:49:30] Requesting new circuit...
Traceback (most recent call last):
  File "/usr/bin/torghost", line 188, in <module>
    switch_tor()
  File "/usr/bin/torghost", line 169, in switch_tor
    with Controller.from_port(port = 9051) as controller:
  File "/usr/local/lib/python2.7/dist-packages/stem/control.py", line 1026, in from_port
    control_port = stem.socket.ControlPort(address, port)
  File "/usr/local/lib/python2.7/dist-packages/stem/socket.py", line 376, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/stem/socket.py", line 247, in connect
    self._socket = self._make_socket()
  File "/usr/local/lib/python2.7/dist-packages/stem/socket.py", line 405, in _make_socket
    raise stem.SocketError(exc)
stem.SocketError: [Errno 111] Connection refused

**Comment by smokescreen42** [comment]
i am having the exact same issue.

how do i uninstall torghost and reinstall it?

how do i reinstall the python package that's giving an issue?

anyone explain?

**Comment by smokescreen42** [comment]
this happened after some sort of dist-upgrade command i did.

**Comment by vivian4uin** [comment]
Same problem !!   is there any Fix ?

**Comment by kalipentest** [comment]
hi 
I had the same problem
But first: 
apt-get update
apt-get upgrade
apt-get install tor 
It's easy to run. No error. Good luck friends

**Comment by igoreduardo** [comment]
Problem resolved
removed torghost
install again torghost
torghost start
CURRENT IP : Not Found
torghost stop
torghot start again
CURRENT IP : SHOW NEW IP

kali 2018.1

**Comment by tonymon7anna101** [comment]
i know how to solve the problem for the trace back error you have to type this in sudo apt-get install tor -y

and with ip error when it does not work if have to cep typing torghost start until it gives you a ip do it 15 times to see if that works

**Comment by mradsgh** [comment]
I have the same issue [errno 111] connection refused, tried all the above... nothing works?

**Comment by guy477** [comment]
In **/etc/proxychain.conf** un-comment **dynamic_chain**.

**Comment by FryerTuck** [comment]
```
    systemctl stop tor
    systemctl enable tor
    systemctl start tor
    torghost start
```

**Comment by FryerTuck** [comment]
On a fresh Kali install:
- `apt-get install python-pip`
- via ssh, make sure your `PATH` var contains `/usr/sbin` or face: `iptables - command not found`

Finally:
```
    systemctl stop tor
    systemctl enable tor
    systemctl start tor
    torghost start
```
Now all should work as expected, if not, install torghost again (after the above) and try again.

**Comment by FryerTuck** [comment]
... been battling with torgost for 3 days now ... it's unstable, hangs, won't stop/start/switch when you tell it to. The real issue that I have with this is that it breaks more often than it works .. it works 10% of the time, the rest is just .... face-desk and try again (and again and again)
