### ISSUE TITLE
Can't install it on Mac

### ISSUE THREAD

**Issue by iocohen** [susmithHCK/torghost#29]
Hi there,

it doesn't install on Mac. Please see below transcript from terminal.

me:torghost-master y0d$ chmod +x install.sh
me:torghost-master y0d$ ./install.sh

******* Torghost installer ********

=====> Installing tor bundle 
Password:
sudo: apt-get: command not found
=====> Installing dependencies 
The directory '/Users/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting stem
  Downloading stem-1.6.0.tar.gz (2.0MB)
    100% |████████████████████████████████| 2.1MB 592kB/s 
Installing collected packages: stem
  Running setup.py install for stem ... done
Successfully installed stem-1.6.0
=====> Installing TorGhost 
cp: /usr/bin/torghost: Operation not permitted
chmod: /usr/bin/torghost: No such file or directory
=====> Done 
=====> Open terminal and type 'torghost' for usage 
me:torghost-master y0d$ torghost
-bash: torghost: command not found
me:torghost-master me$ torghost start
-bash: torghost: command not found
me:torghost-master me$

**Comment by Funeoz** [comment]
It only works on Linux based OS. It will not works on Mac
