### ISSUE TITLE
can be use it with metasploit or empire?

### ISSUE THREAD

**Issue by HackM3nt3** [susmithHCK/torghost#5]
I was checking your website and i saw a post about backdoor factory, and i remembered that Josh Pitts, the autor of BDF made a post about using tor and empire, so i was asking myself, Is it possible use torghost with metasploit or empire and how this can be done?

Or can you point me the right direction in this particular topic?

**Comment by susmithHCK** [comment]
You mean connecting a shell via tor network?

**Comment by HackM3nt3** [comment]
yes, joss pitts showed here, http://secureallthethings.blogspot.com, but the post is incomplete, so can it be done using torghost? and how?

**Comment by NourEddineX** [comment]
@HackM3nt3 please inform me if you could do it
