### ISSUE TITLE
Won't work on Archlinux because of the shebang

### ISSUE THREAD

**Issue by NourEddineX** [susmithHCK/torghost#7]
change the shebang to
`#!/usr/bin/python2` instead of `#!/usr/bin/python`

( python command in Archlinux execute as python3 )

**Comment by jmfgdev** [comment]
be careful @NourEddineX Susmith doesn't believe me that this repo is totally leaking DNS requests. I think he has only tried it on a limited variety of deployments. This package is not safe as it doesn't use TorDNS. The author hasn't read the Arch Linux wiki about Tor where it clearly states that extra configuration is needed to enable TorDNS. Yet when I brought it up he denied it and then ignored it.
